### ISSUE TITLE
alpha in geom_label_npc() only works if data.frame is provided

### ISSUE THREAD

**Issue by RS-eco** [cran/ggpmisc#3]
I am trying to add a semi-transparent label to a plot using the geom_label_npc() function. Unfortunately, this does not seem to work, when I directly provide npcx, npcy and the label argument:

```{r}
library(ggplot2); library(ggpmisc)

ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label_npc(npcx=0.04, npcy=0.95, label="(a)", colour="white", alpha = 0.5) 
```

However, it seems to work, if I provide the same values inside a data.frame object:

```{r}
df <- data.frame(
  x = 0.04,
  y = c(0.95),
  text = c("(a)")
)

ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label_npc(data = df, aes(npcx = x, npcy = y, label = text), colour="white", alpha=0.5)
```

Is probably a small bug, that can easily be solved.

**Comment by RS-eco** [comment]
And another question, is there any way to use geom_label_npc() without the a border around the label or give the border a different colour to the text?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and potentially URLs in the `DESCRIPTION` file. Thanks!
